spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27016
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
server:
  port: 0
queue:
  movie:
    name: my-movie-queue
  serie:
    name: my-serie-queue
